# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninegag',
            name='imagevideo_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ninegag',
            name='source_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ninegag',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
