# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninegag',
            old_name='imagevideo',
            new_name='imagevideo_path',
        ),
    ]
