# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0002_auto_20160608_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninegag',
            name='imagevideo_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ninegag',
            name='source_url',
            field=models.CharField(max_length=200),
        ),
    ]
