# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0004_ninegag_is_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninegag',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
