# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0006_auto_20160609_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninegag',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male')], default=None, max_length=1, null=True, verbose_name='Are you male or female?'),
        ),
    ]
