# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0009_joke_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
