# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0015_auto_20160609_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='category',
        ),
    ]
