# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0016_remove_joke_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='text',
        ),
    ]
