# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfly', '0017_auto_20160609_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joke',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joke',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
