# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('funfly', '0022_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='added_at',
            field=models.DateTimeField(null=True),
        ),
    ]
