# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('funfly', '0024_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(),
        ),
    ]
