# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('funfly', '0027_auto_20160612_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
