# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('funfly', '0028_joke_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
